# Generated by Django 3.2.3 on 2021-05-13 11:12

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='columns',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('pos', models.IntegerField(default=0, verbose_name='Позиция в столбце')),
                ('id_parent', models.UUIDField(blank=True, default=app.models.generate_uuid, null=True, verbose_name='Родительский итем')),
                ('id_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код')),
                ('is_act', models.BooleanField(default=False, null=True, verbose_name='Is act')),
                ('direction', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Столбец в таблице')),
                ('startech', models.IntegerField(blank=True, default=-1, null=True, verbose_name='Стартовая строка')),
            ],
            options={
                'verbose_name': 'Данные столбца',
                'verbose_name_plural': 'Данные столбцов',
            },
        ),
        migrations.CreateModel(
            name='example',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(blank=True, default='', null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
            },
        ),
        migrations.CreateModel(
            name='header_data',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Наименование строки')),
                ('actual_d', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Актуальная дата')),
            ],
            options={
                'verbose_name': 'Наименование столбца',
                'verbose_name_plural': 'Наименования столбцов',
            },
        ),
        migrations.CreateModel(
            name='indicator_data',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Наименование строки')),
                ('actual_d', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Актуальная дата')),
            ],
            options={
                'verbose_name': 'Наименование строки',
                'verbose_name_plural': 'Наименования строк',
            },
        ),
        migrations.CreateModel(
            name='passports',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('actual_d', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Актуальная дата')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорты',
            },
        ),
        migrations.CreateModel(
            name='spr_forms',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='spr_chapters',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('number_f', models.TextField(verbose_name='Номер четверти')),
                ('repository_addres', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Адрес репозитория')),
                ('type', models.TextField(blank=True, default='', null=True, verbose_name='Тип')),
                ('position', models.IntegerField(blank=True, default=0, null=True, verbose_name='Позиция')),
                ('store', models.JSONField(blank=True, default='', null=True, verbose_name='Данные')),
                ('id_forms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.spr_forms', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Четверть',
                'verbose_name_plural': 'Четверти',
            },
        ),
        migrations.CreateModel(
            name='rows',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('pos', models.IntegerField(default=0, verbose_name='Позиция в строке')),
                ('id_parent', models.UUIDField(blank=True, default=app.models.generate_uuid, null=True, verbose_name='Родительский итем')),
                ('id_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код')),
                ('is_define', models.BooleanField(blank=True, default=False, null=True, verbose_name='Определение?')),
                ('dimension', models.TextField(blank=True, default='', null=True, verbose_name='Размерность')),
                ('direction', models.IntegerField(blank=True, default=0, null=True, verbose_name='Строка в таблице')),
                ('id_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.spr_chapters', verbose_name='Четверть')),
                ('id_indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.indicator_data', verbose_name='Наименование строки')),
            ],
            options={
                'verbose_name': 'Данные строки',
                'verbose_name_plural': 'Данные строк',
            },
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('icol', models.IntegerField(default=0, null=True, verbose_name='Номер информационного столбца')),
                ('id_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.spr_chapters', verbose_name='Наименование строки')),
                ('id_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.columns', verbose_name='Наименование строки')),
                ('id_row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rows', verbose_name='Наименование строки')),
            ],
            options={
                'verbose_name': 'Запись в таблице',
                'verbose_name_plural': 'Записи в таблице',
            },
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='Имя файла')),
                ('id_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.spr_chapters', verbose_name='Четверть')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.UUIDField(default=app.models.generate_uuid, primary_key=True, serialize=False, verbose_name='id')),
                ('data', models.TextField(blank=True, default='', null=True, verbose_name='Информация')),
                ('row_uuid', models.UUIDField(blank=True, default=0, null=True, verbose_name='UUID строки')),
                ('nrow', models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер строки')),
                ('id_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.spr_chapters', verbose_name='Четверть')),
                ('passport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.passports', verbose_name='Паспорт')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.records', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Массив данных',
                'verbose_name_plural': 'Массивы данных',
            },
        ),
        migrations.AddField(
            model_name='columns',
            name='id_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.spr_chapters', verbose_name='Четверть'),
        ),
        migrations.AddField(
            model_name='columns',
            name='id_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.header_data', verbose_name='Наименование столбца'),
        ),
    ]
